# Generated by Django 4.0.2 on 2022-03-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employ_category',
            field=models.CharField(choices=[('man', 'manager'), ('sup', 'supervisor'), ('hke', 'house keeping employee')], default='hke', max_length=5),
        ),
    ]
