# Generated by Django 4.0.2 on 2022-03-09 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_employ_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='employ_category',
            new_name='employee_category',
        ),
    ]
