# Generated by Django 4.0.1 on 2022-01-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
