# Generated by Django 4.0.2 on 2022-03-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_employee_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_category',
            field=models.CharField(blank=True, choices=[('1', 'manager'), ('2', 'supervisor'), ('3', 'house keeping employee')], max_length=5, null=True, verbose_name='category'),
        ),
    ]
