# Generated by Django 4.0.2 on 2022-03-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_employee_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_category',
            field=models.CharField(choices=[('1', 'manager'), ('2', 'supervisor'), ('3', 'house keeping employee')], default='hke', max_length=10),
            preserve_default=False,
        ),
    ]
