# Generated by Django 4.0.1 on 2022-02-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile2_remove_profile_date_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile2',
        ),
    ]
